import { Poppins } from 'next/font/google';
import './globals.css';
import Provider from '../providers';

const poppinsLight = Poppins({ subsets: ['latin'], weight: '400' });

export const metadata = {
  title: 'Mini Project JCWDOL',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppinsLight.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
